// Generated by the LibSL translator.  DO NOT EDIT!
// sources:
//  - ???
//
import {SymbolicList} from '@org.usvm.api';


export namespace lsl$concepts {

    /**
     * libsl/LSL_ListIterator.main.lsl:17 */
    export interface LSL_ListContainer<T> {

        storage: SymbolicList<T>;

    }

}
