// Generated by the LibSL translator.  DO NOT EDIT!
// sources:
//  - ???
//
import {libsl_globals} from './libsl_globals';
import {Approximate} from '@org.jacodb.approximation.annotation';


@Approximate(/* value */ libsl_globals)
export class libsl_globals_gen {
}
