// Generated by the LibSL translator.  DO NOT EDIT!
// sources:
//  - libsl/LSL_MapIterator.lsl:25
//  - libsl/LSL_MapIterator_V.main.lsl:18
//

export class LSL_MapIterator_V<V> {

    next(): IteratorResult<V> {
        let lsl$e = new SyntaxError();
        lsl$e.name = 'LinkingError';
        throw lsl$e;
    }

    [Symbol.iterator](): IterableIterator<V> {
        let lsl$e = new SyntaxError();
        lsl$e.name = 'LinkingError';
        throw lsl$e;
    }

}
