// Generated by the LibSL translator.  DO NOT EDIT!
// sources:
//  - libsl/LSL_MapIterator.lsl:15
//

export class LSL_MapIterator_K<K> {

    next(): IteratorResult<K> {
        let lsl$e = new SyntaxError();
        lsl$e.name = 'LinkingError';
        throw lsl$e;
    }

    [Symbol.iterator](): IterableIterator<K> {
        let lsl$e = new SyntaxError();
        lsl$e.name = 'LinkingError';
        throw lsl$e;
    }

}
