// Generated by the LibSL translator.  DO NOT EDIT!
// sources:
//  - libsl/LSL_MapIterator.lsl:45
//

export class LSL_MapIterator_tupleKV<K, V> {

    next(): IteratorResult<[K, V]> {
        let lsl$e = new SyntaxError();
        lsl$e.name = 'LinkingError';
        throw lsl$e;
    }

    [Symbol.iterator](): IterableIterator<[K, V]> {
        let lsl$e = new SyntaxError();
        lsl$e.name = 'LinkingError';
        throw lsl$e;
    }

}
