// Generated by the LibSL translator.  DO NOT EDIT!
// sources:
//  - libsl/LSL_MapIterator.lsl:35
//  - libsl/LSL_MapIterator_tupleKK.main.lsl:18
//

export class LSL_MapIterator_tupleKK<K> {

    next(): IteratorResult<[K, K]> {
        let lsl$e = new SyntaxError();
        lsl$e.name = 'LinkingError';
        throw lsl$e;
    }

    [Symbol.iterator](): IterableIterator<[K, K]> {
        let lsl$e = new SyntaxError();
        lsl$e.name = 'LinkingError';
        throw lsl$e;
    }

}
