// Generated by the LibSL translator.  DO NOT EDIT!
// sources:
//  - libsl/LSL_IteratorResult.lsl:16
//  - libsl/LSL_IteratorResult.main.lsl:16
//
import {libsl} from './libsl_runtime';


export class LSL_IteratorResult<T> {

    done: boolean = false;

    value: T = libsl.ANYTHING;

}
