// Generated by the LibSL translator.  DO NOT EDIT!
// sources:
//  - libsl/LSL_MapIterator.lsl:56
//

export class LSL_MapIterator_tupleVV<V> {

    next(): IteratorResult<[V, V]> {
        let lsl$e = new SyntaxError();
        lsl$e.name = 'LinkingError';
        throw lsl$e;
    }

    [Symbol.iterator](): IterableIterator<[V, V]> {
        let lsl$e = new SyntaxError();
        lsl$e.name = 'LinkingError';
        throw lsl$e;
    }

}
