// Generated by the LibSL translator.  DO NOT EDIT!
// sources:
//  - libsl/LSL_IteratorResult.lsl:16
//  - libsl/LSL_IteratorResult.main.lsl:16
//
import {LSL_IteratorResult} from './LSL_IteratorResult';
import {libsl} from './libsl_runtime';
import {Approximate} from '@org.jacodb.approximation.annotation';


/**
 * LSL_IteratorResultAutomaton for LSL_IteratorResult<T> ~> LSL_IteratorResult@LSL_IteratorResult */
@Approximate(/* value */ LSL_IteratorResult)
export class LSL_IteratorResultAutomaton<T> {

    done: boolean = false;

    value: T | undefined = libsl.ANYTHING;

}
