// Generated by the LibSL translator.  DO NOT EDIT!
// sources:
//  - libsl/LSL_ListIterator.lsl:15
//

export class LSL_ListIterator<T> {

    next(): IteratorResult<T> {
        let lsl$e = new SyntaxError();
        lsl$e.name = 'LinkingError';
        throw lsl$e;
    }

    [Symbol.iterator](): IterableIterator<T> {
        let lsl$e = new SyntaxError();
        lsl$e.name = 'LinkingError';
        throw lsl$e;
    }

}
