// Generated by the LibSL translator.  DO NOT EDIT!
// sources:
//  - ohos/util/PlainArray.lsl:46
//  - ohos/util/PlainArray.Iterator_tupleKV.lsl:17
//

export class PlainArray_Iterator_tupleKV<K, V> {

    next(): IteratorResult<[K, V]> {
        let lsl$e = new SyntaxError();
        lsl$e.name = 'LinkingError';
        throw lsl$e;
    }

    [Symbol.iterator](): IterableIterator<[K, V]> {
        let lsl$e = new SyntaxError();
        lsl$e.name = 'LinkingError';
        throw lsl$e;
    }

}
